name: Release


on:
  pull_request:
  push:
    branches:
      - main
    tags:
      - '*'

jobs:
  release-container:
    uses: radiorabe/actions/.github/workflows/release-container.yaml@479996126a091287dc3fd349786f6f8a6dd1b23c # v0.42.0
    with:
      image: ghcr.io/radiorabe/nut-exporter
      name: nut-exporter
      display-name: RaBe NUT Exporter
      tags: minimal rhel9 ubi9 nut nut-exporter
      cosign-verify: true
      cosign-base-image-only: true
  release-mkdocs:
    permissions:
      contents: write # Required to push the gh-pages branch for documentation deployment
    uses: radiorabe/actions/.github/workflows/release-mkdocs.yaml@479996126a091287dc3fd349786f6f8a6dd1b23c # v0.42.0
  github-actions:
    permissions:
      contents: read
      security-events: write # so zizmor can publish results to the Security tab
    uses: radiorabe/actions/.github/workflows/test-github-actions.yaml@479996126a091287dc3fd349786f6f8a6dd1b23c # v0.42.0
